Repository Activiti/activiti-cloud, pull requests merged in 2023-05, with the labels that each got.

#1075 [AAE-14012] new content type
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/resources/schema/process-extensions-schema.json
Labels: next-version

#1067 Fix concurrency exception in modeling service
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/pom.xml
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/service/ModelingServiceAutoConfiguration.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/ConnectorModelValidator.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/JsonSchemaModelValidator.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/JsonSchemaModelValidatorConfiguration.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/ProcessModelValidatorConfiguration.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/extensions/ExtensionsModelValidator.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/extensions/ProcessExtensionsModelValidator.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/ConnectorModelValidatorIT.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/validation/ValidatorConcurrencyIntegrationTest.java
Labels: bug

#1076 AAE-14054 upgrade base example-cloud-connector image
  activiti-cloud-examples/example-cloud-connector/Dockerfile
Labels: dependencies

#1071 AAE-13446 fix audit integration events timestamps
  activiti-cloud-api/activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudIntegrationErrorReceivedEventImpl.java
  activiti-cloud-api/activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudIntegrationEventImpl.java
  activiti-cloud-api/activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudIntegrationRequestedEventImpl.java
  activiti-cloud-api/activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/events/CloudIntegrationResultReceivedEventImpl.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/IntegrationErrorReceivedEventConverter.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/IntegrationRequestedEventConverter.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/converters/IntegrationResultReceivedEventConverter.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/converters/IntegrationErrorReceivedEventConverterTest.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/converters/IntegrationRequestedEventConverterTest.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/converters/IntegrationResultReceivedEventConverterTest.java
Labels: bug

#1081 Fix flaky tests
  activiti-cloud-messages-service/integration-tests/src/test/java/org/activiti/cloud/messages/integration/tests/events/MessageEventsIT.java
  activiti-cloud-messages-service/integration-tests/src/test/java/org/activiti/cloud/messages/integration/tests/rb/MultipleRbMessagesIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/JobExecutorIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ProcessInstanceIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/AuditProducerIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/MessageAuditProducerIT.java
  activiti-cloud-service-common/activiti-cloud-services-test-security/src/main/java/org/activiti/cloud/services/test/identity/listener/KeycloakTokenProducerCleanListener.java
  activiti-cloud-service-common/activiti-cloud-services-test-security/src/main/resources/META-INF/spring.factories
Labels: bug

#1089 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1087 AAE-14299 extend keycloak client api for pagination
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/client/KeycloakClient.java
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/test/java/org/activiti/cloud/services/identity/keycloak/KeycloakClientApplication.java
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/test/java/org/activiti/cloud/services/identity/keycloak/KeycloakClientIT.java
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/test/java/org/activiti/cloud/services/identity/keycloak/TestKeycloakClient.java
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/test/java/org/activiti/cloud/services/identity/keycloak/TestKeycloakUser.java
  activiti-cloud-service-common/activiti-cloud-services-test-containers/src/main/resources/activiti-realm.json
  activiti-cloud-service-common/activiti-cloud-services-test-security/src/main/java/org/activiti/cloud/identity/web/controller/AbstractIdentityManagementControllerIT.java
Labels: bug

#1102 Remove nimbus-jose-jwt shaded dependencies
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/mapper/KeycloakTokenToUserRoles.java
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/test/java/org/activiti/cloud/services/identity/keycloak/mapper/KeycloakTokenToUserRolesTest.java
  activiti-cloud-service-common/activiti-cloud-services-common-security-keycloak/src/main/java/org/activiti/cloud/services/common/security/keycloak/KeycloakJwtAdapter.java
  activiti-cloud-service-common/activiti-cloud-services-common-security-keycloak/src/main/java/org/activiti/cloud/services/common/security/keycloak/KeycloakResourceJwtAdapter.java
  activiti-cloud-service-common/activiti-cloud-services-common-security-keycloak/src/test/java/org/activiti/cloud/services/common/security/keycloak/KeycloakJwtAdapterTest.java
  activiti-cloud-service-common/activiti-cloud-services-common-security-keycloak/src/test/java/org/activiti/cloud/services/common/security/keycloak/KeycloakResourceJwtAdapterTest.java
  activiti-cloud-service-common/activiti-cloud-services-test-security/src/main/java/org/activiti/cloud/services/common/security/test/support/WithActivitiMockUserSecurityContextFactory.java
  activiti-cloud-service-common/activiti-cloud-services-test-security/src/main/java/org/activiti/cloud/services/common/security/test/support/keycloak/KeycloakRolesClaimProvider.java
Labels: bug, preview
