Repository Activiti/activiti-cloud, pull requests merged in 2023-06, with the labels that each got.

#1107 AAE-15056 Fix GraphQL Query Service to format date with time in ISO-8061
  activiti-cloud-notifications-graphql-service/services/jpa-query/src/main/java/org/activiti/cloud/services/notifications/graphql/jpa/query/ActivitiGraphQLSchemaAutoConfiguration.java
  activiti-cloud-notifications-graphql-service/services/jpa-query/src/test/java/org/activiti/cloud/services/notifications/graphql/jpa/query/ActivitiGraphQLSchemaAutoConfigurationTest.java
Labels: bug

#1108 AAE-10754 Migrate Activiti maven projects to JDK 17
  .github/workflows/main.yml
  Makefile
  activiti-cloud-acceptance-scenarios/pom.xml
  activiti-cloud-acceptance-scenarios/runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/story/ProcessInstanceTasks.java
  activiti-cloud-acceptance-tests/activiti-cloud-acceptance-tests-core/pom.xml
  activiti-cloud-acceptance-tests/activiti-cloud-acceptance-tests-shared/pom.xml
  activiti-cloud-acceptance-tests/activiti-cloud-acceptance-tests-shared/src/main/java/org/activiti/cloud/acc/shared/serenity/ExtendedSerenityStories.java
  activiti-cloud-acceptance-tests/pom.xml
  activiti-cloud-api/pom.xml
  activiti-cloud-dependencies/pom.xml
  activiti-cloud-examples/activiti-cloud-identity-adapter/Dockerfile
  activiti-cloud-examples/activiti-cloud-identity-adapter/entrypoint.sh
  activiti-cloud-examples/activiti-cloud-modeling/Dockerfile
  activiti-cloud-examples/activiti-cloud-modeling/entrypoint.sh
  activiti-cloud-examples/activiti-cloud-modeling/liquibase/pom.xml
  activiti-cloud-examples/activiti-cloud-query/Dockerfile
  activiti-cloud-examples/activiti-cloud-query/entrypoint.sh
  activiti-cloud-examples/activiti-cloud-query/liquibase/pom.xml
  activiti-cloud-examples/example-cloud-connector/Dockerfile
  activiti-cloud-examples/example-runtime-bundle/Dockerfile
  activiti-cloud-examples/pom.xml
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-jpa/src/main/java/org/activiti/cloud/services/modeling/jpa/config/ModelingJpaAutoConfiguration.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-jpa/src/test/java/org/activiti/cloud/services/modeling/jpa/audit/AuditorAwareIT.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
  pom.xml
Labels: next-version, preview

#1122 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1123 AAE-15222 - Add aws binder option
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/ActivitiCloudMessagingProperties.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-starter/src/main/java/org/activiti/cloud/common/messaging/config/ActivitiMessagingEnvironmentPostProcessor.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-starter/src/test/java/org/activiti/cloud/common/messaging/config/ActivitiMessagingEnvironmentPostProcessorTest.java
Labels: enhancement

#1098 AAE-15142 testcontainer reuse
  .github/workflows/main.yml
  activiti-cloud-messages-service/integration-tests/src/test/java/org/activiti/cloud/messages/integration/tests/rb/MultipleRbMessagesIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle-it/src/test/java/org/activiti/cloud/starter/tests/jobexecutor/MultipleRbJobExecutorIT.java
  activiti-cloud-service-common/activiti-cloud-services-test-containers/src/main/java/org/activiti/cloud/services/test/containers/KeycloakContainerApplicationInitializer.java
  activiti-cloud-service-common/activiti-cloud-services-test-containers/src/main/java/org/activiti/cloud/services/test/containers/RabbitMQContainerApplicationInitializer.java
Labels: enhancement

#1124 AAE-15305 Upgrade Activiti Cloud to Spring Boot 3.1
  activiti-cloud-api/pom.xml
  activiti-cloud-build/activiti-cloud-build-dependencies-parent/pom.xml
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-jpa/src/main/java/org/activiti/cloud/services/modeling/entity/ModelEntity.java
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-notifications-graphql-service/pom.xml
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/QueryEventHandlerContextOptimizer.java
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/activiti-cloud-services-common-security/src/test/java/org/activiti/cloud/security/authorization/AuthorizationConfigurerTest.java
  activiti-cloud-service-common/pom.xml
  pom.xml
Labels: dependencies, preview

#1130 Revert "[AAE-7344] Fix BpmnCommonModelValidator (#1117)"
  activiti-cloud-modeling-service/activiti-cloud-acceptance-tests-modeling/src/main/java/org/activiti/cloud/acc/modeling/steps/ModelingModelsSteps.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/java/org/activiti/cloud/services/modeling/rest/controller/ModelControllerIT.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-rest/src/test/java/org/activiti/cloud/services/modeling/rest/controller/ModelValidationControllerIT.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/validation/process/BpmnModelUserTaskAssigneeValidator.java
Labels: invalid

#1132 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1139 Revert "[AAE-9137] Fix imported project version (#1104)"
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-jpa/src/main/java/org/activiti/cloud/services/modeling/jpa/ModelRepositoryImpl.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-jpa/src/test/java/org/activiti/cloud/services/modeling/jpa/ModelRepositoryImplTest.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-repository/src/main/java/org/activiti/cloud/modeling/repository/ModelRepository.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/service/ModelServiceImpl.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/service/ProjectServiceImpl.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/main/java/org/activiti/cloud/services/modeling/service/api/ModelService.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/service/ModelServiceImplTest.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/src/test/java/org/activiti/cloud/services/modeling/service/ProjectServiceImplTest.java
Labels: bug

#1140 AAE-15527 Update Alfresco DBP REST default media format to application/json
  activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/main/resources/config/alfresco-rest-config.properties
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/test/resources/org/activiti/cloud/common/swagger/apidocs/springdoc-api-docs.json
Labels: bug
