Repository Activiti/activiti-cloud, pull requests merged in 2023-09, with the labels that each got.

#1197 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1198 fix(versions): update Activiti/activiti-cloud versions into 7.11.x
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1199 fix(versions): update Activiti/activiti-cloud versions into 7.11.x
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1203 AAE-16060 avoid triggering Create Pre-release workflow on rc tag [skip ci]
  .github/workflows/create-github-prerelease.yaml
Labels: github_actions

#1204 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1205 [AAE-16572] - upgrade spring-boot to 3.1.3 and spring-cloud to 2022.0.4 to fix vulnerability in spring-kafka 3.0.8
  activiti-cloud-build/activiti-cloud-build-dependencies-parent/pom.xml
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-service/pom.xml
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/pom.xml
  pom.xml
Labels: preview

#1212 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1214 fix(versions): update Activiti/activiti-cloud versions into 7.11.x
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot
