Repository Activiti/activiti-cloud, pull requests merged in 2023-07, with the labels that each got.

#1146 Fix IntegrationError handler
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/src/main/java/org/activiti/services/connectors/channel/ServiceTaskIntegrationErrorEventHandler.java
Labels: preview

#1148 AAE-15538 fix snappy vulnerable version
  activiti-cloud-service-common/activiti-cloud-service-common-dependencies/pom.xml
Labels: dependencies

#1092 [AAE-14288] sempgrep integration to detect usage of spring componentScan
  .pre-commit-config.yaml
  .sempgrep.yaml
Labels: next-version

#1155 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1161 [AAE-9137] Fix imported project version
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-jpa/src/main/java/org/activiti/cloud/services/modeling/jpa/ModelRepositoryImpl.java
  activiti-cloud-modeling-service/activiti-cloud-services-modeling/activiti-cloud-services-modeling-jpa/src/test/java/org/activiti/cloud/services/modeling/jpa/ModelRepositoryImplTest.java
Labels: do-not-merge
