Repository Activiti/activiti-cloud, pull requests merged in 2024-05, with the labels that each got.

#1432 chore(deps): upgrade Activiti/Activiti to version 8.5.0-alpha.2
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1438 AAE-22485 Update graphql-jpa-query.version to 1.2.5
  activiti-cloud-notifications-graphql-service/pom.xml
Labels: bug

#1439 chore(deps): upgrade Activiti/Activiti to version 8.5.0-alpha.3
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1442 chore(deps): upgrade Activiti/Activiti to version 8.5.0-alpha.4
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1450 AAE-22508 Add capability to query aggregated data in GraphQL queries
  activiti-cloud-notifications-graphql-service/pom.xml
  activiti-cloud-notifications-graphql-service/services/jpa-query/src/main/java/org/activiti/cloud/services/notifications/graphql/jpa/query/ActivitiGraphQLSchemaAutoConfiguration.java
  activiti-cloud-notifications-graphql-service/starter/src/test/java/org/activiti/cloud/notifications/graphql/starter/ActivitiGraphQLStarterIT.java
  activiti-cloud-notifications-graphql-service/starter/src/test/resources/data.sql
Labels: enhancement

#1452 chore(deps): upgrade Activiti/Activiti to version 8.6.0-alpha.1
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1454 chore(deps): upgrade Activiti/Activiti to version 8.6.0-alpha.2
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1453 AAE-22508 Add inline documentation for aggregated data in GraphQL query shema
  activiti-cloud-notifications-graphql-service/pom.xml
  activiti-cloud-notifications-graphql-service/starter/src/test/java/org/activiti/cloud/notifications/graphql/starter/ActivitiGraphQLStarterIT.java
Labels: enhancement
