Repository Activiti/activiti-cloud, pull requests merged in 2024-10, with the labels that each got.

#1560 AAE-26198 Fix slow GraphQl query performance due to redundant JPA fetch query with empty keys
  activiti-cloud-notifications-graphql-service/pom.xml
Labels: bug

#1550 AAE-25958 Fix Query Service OOM errors caused by infinite/unbounded service tasks instances
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-events/src/main/java/org/activiti/cloud/services/query/events/handlers/QueryEventHandlerContextOptimizer.java
Labels: bug

#1539 AAE-23175 Upgrade testcontainers-keycloak to 3.3.1
  activiti-cloud-service-common/activiti-cloud-services-test-containers/pom.xml
  activiti-cloud-service-common/activiti-cloud-services-test-containers/src/main/java/org/activiti/cloud/services/test/containers/KeycloakContainerApplicationInitializer.java
  activiti-cloud-service-common/activiti-cloud-services-test-containers/src/test/java/org/activiti/cloud/services/test/containers/KeycloakContainerApplicationInitializerIT.java
  activiti-cloud-service-common/activiti-cloud-services-test-containers/src/test/java/org/activiti/cloud/services/test/containers/TestContainersApplication.java
Labels: dependencies, preview

#1564 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.26
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1565 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.27
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1573 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.28
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1572 AAE-26793 Add Acceptance Tests for Query and Consumer with PDB deployment enabled
  .github/workflows/main.yml
  activiti-cloud-examples/activiti-cloud-query/config/pom.xml
  activiti-cloud-examples/activiti-cloud-query/config/src/main/java/org/activiti/cloud/query/configuration/QueryConfiguration.java
  activiti-cloud-examples/activiti-cloud-query/config/src/main/resources/activiti-cloud-query-config.properties
  activiti-cloud-examples/activiti-cloud-query/consumer/pom.xml
  activiti-cloud-examples/activiti-cloud-query/consumer/src/main/resources/application.properties
  activiti-cloud-examples/activiti-cloud-query/consumer/src/test/java/org/activiti/cloud/query/consumer/QueryConsumerApplicationIT.java
  activiti-cloud-examples/activiti-cloud-query/consumer/src/test/resources/logback-test.xml
  activiti-cloud-examples/activiti-cloud-query/liquibase/pom.xml
  activiti-cloud-examples/activiti-cloud-query/pom.xml
  activiti-cloud-examples/activiti-cloud-query/rest/pom.xml
  activiti-cloud-examples/activiti-cloud-query/rest/src/main/resources/application.properties
  activiti-cloud-examples/activiti-cloud-query/rest/src/test/java/org/activiti/cloud/query/rest/QueryRestApplicationIT.java
  activiti-cloud-examples/activiti-cloud-query/rest/src/test/resources/logback-test.xml
  activiti-cloud-examples/activiti-cloud-query/starter/pom.xml
  activiti-cloud-examples/activiti-cloud-query/starter/src/main/resources/application.properties
  activiti-cloud-examples/activiti-cloud-query/starter/src/test/java/org/activiti/cloud/query/QueryApplicationIT.java
  activiti-cloud-examples/activiti-cloud-query/starter/src/test/resources/application.properties
  activiti-cloud-query-service/activiti-cloud-starter-query-rest/pom.xml
Labels: enhancement

#1579 AAE-26860 Enforce dependencies for Query Consumer and Rest applications
  activiti-cloud-examples/activiti-cloud-query/consumer/pom.xml
  activiti-cloud-examples/activiti-cloud-query/rest/pom.xml
Labels: enhancement

#1584 AAE-22831 Fix NPE regression when deleting cancelled process instance
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/listeners/ProcessEngineEventsAggregator.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ProcessInstanceIT.java
Labels: bug

#1541 AAE-25756 Add Query service schema index for task id,name and status attributes
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-liquibase/src/main/resources/config/query/liquibase/changelog/28-alter.oracle.schema.8.7.0.sql
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-liquibase/src/main/resources/config/query/liquibase/changelog/28-alter.pg.schema.8.7.0.sql
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-liquibase/src/main/resources/config/query/liquibase/changelog/h2.schema.sql
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-liquibase/src/main/resources/config/query/liquibase/master.xml
Labels: enhancement
