Repository Activiti/activiti-cloud, pull requests merged in 2024-03, with the labels that each got.

#1381 AAE-20915 Refactor non-compliant legacy cloud stream error handler for functional connector bindings
  activiti-cloud-connectors/activiti-cloud-starter-connector/src/main/java/org/activiti/cloud/connectors/starter/channels/IntegrationErrorHandlerImpl.java
  activiti-cloud-connectors/activiti-cloud-starter-connector/src/main/java/org/activiti/cloud/connectors/starter/channels/IntegrationRequestErrorChannelListener.java
  activiti-cloud-connectors/activiti-cloud-starter-connector/src/main/resources/activiti-cloud-connector.properties
  activiti-cloud-connectors/activiti-cloud-starter-connector/src/test/java/org/activiti/cloud/connectors/starter/test/it/ActivitiCloudConnectorServiceIT.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/ConnectorConfiguration.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/FunctionBindingConfiguration.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ConnectorConfigurationIT.java
Labels: bug

#1387 AAE-20974 Fix Idempotent Bpmn messages receiver interceptor configuration from discarding duplicate messages into the error channel
  activiti-cloud-messages-service/services/core/src/main/java/org/activiti/cloud/services/messages/core/config/MessagesCoreAutoConfiguration.java
  activiti-cloud-messages-service/services/tests/src/test/java/org/activiti/cloud/services/messages/tests/AbstractMessagesCoreIntegrationTests.java
Labels: bug

#1389 chore(deps): upgrade Activiti/Activiti to version 8.4.0-alpha.1
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1390 chore(deps): upgrade Activiti/Activiti to version 8.4.0-alpha.2
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1393 AAE-21015 Fix dispatcher has no subscribers for channel 'rb.discardChannel' error log message
  activiti-cloud-messages-service/services/core/src/main/java/org/activiti/cloud/services/messages/core/config/MessagesCoreAutoConfiguration.java
  activiti-cloud-messages-service/services/core/src/test/java/org/activiti/cloud/services/messages/test/core/MessageCoreAutoConfigurationTest.java
Labels: bug

#1394 chore(deps): upgrade Activiti/Activiti to version 8.4.0-alpha.3
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1396 chore(deps): upgrade Activiti/Activiti to version 8.4.0-alpha.4
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1405 chore(deps): upgrade Activiti/Activiti to version 8.4.0-alpha.5
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1403 AAE-21177 Added hideDisabledUser parameter to user search, implemente…
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/KeycloakManagementService.java
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/model/KeycloakUser.java
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/test/java/org/activiti/cloud/services/identity/keycloak/KeycloakClientIT.java
  activiti-cloud-service-common/activiti-cloud-services-common-security/src/main/java/org/activiti/cloud/identity/UserSearchParams.java
  activiti-cloud-service-common/activiti-cloud-services-common-security/src/main/java/org/activiti/cloud/identity/web/controller/IdentityManagementController.java
  activiti-cloud-service-common/activiti-cloud-services-test-containers/src/main/resources/activiti-realm.json
  activiti-cloud-service-common/activiti-cloud-services-test-security/src/main/java/org/activiti/cloud/identity/web/controller/AbstractIdentityManagementControllerIT.java
Labels: enhancement

#1406 chore(deps): upgrade Activiti/Activiti to version 8.4.0-alpha.6
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1407 chore(deps): upgrade Activiti/Activiti to version 8.4.0-alpha.7
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop
