Repository Activiti/activiti-cloud, pull requests merged in 2024-01, with the labels that each got.

#1309 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1312 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1311 AAE-19196 support for java date+time
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/pom.xml
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/MapOfStringObjectJsonConverter.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/src/test/java/org/activiti/cloud/services/query/model/MapOfStringObjectJsonConverterTest.java
Labels: preview

#1296 AAE-19031 juel module removed
  activiti-cloud-examples/activiti-cloud-modeling/pom.xml
  activiti-cloud-examples/activiti-cloud-modeling/src/main/java/org/activiti/cloud/modeling/ModelingApplication.java
  activiti-cloud-modeling-service/activiti-cloud-modeling-dependencies/pom.xml
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/pom.xml
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/main/java/org/activiti/cloud/starter/juel/configuration/ActivitiJuelAutoConfiguration.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/main/java/org/activiti/cloud/starter/juel/configuration/EnableActivitiJuel.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/main/java/org/activiti/cloud/starter/juel/configuration/JuelRestConfiguration.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/main/java/org/activiti/cloud/starter/juel/configuration/JuelSwaggerConfig.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/main/java/org/activiti/cloud/starter/juel/controller/JuelExpressionResolverController.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/main/java/org/activiti/cloud/starter/juel/exception/JuelRuntimeException.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/main/java/org/activiti/cloud/starter/juel/service/JuelExpressionResolverService.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/main/resources/juel.properties
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/test/java/org/activiti/cloud/starter/juel/JuelExpressionApp.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/test/java/org/activiti/cloud/starter/juel/service/JuelExpressionResolverServiceTest.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/test/java/org/activiti/cloud/starter/juel/swagger/JuelSwaggerIT.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/test/java/org/activiti/cloud/starter/juel/swagger/JuelSwaggerITSupport.java
  activiti-cloud-modeling-service/activiti-cloud-starter-juel/src/test/resources/application.properties
  activiti-cloud-modeling-service/pom.xml
Labels: preview

#1313 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1316 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1317 AAE-18268 Fix regression for Hibernate HHH000104 firstResult/maxResults warning in Query
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-repo/src/main/java/org/activiti/cloud/services/query/app/repository/ProcessInstanceRepository.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceAdminService.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceService.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessInstancesEntityIT.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/resources/application-test.properties
Labels: bug, preview

#1320 Update graphql-jpa-query dependency version to 1.2.3
  activiti-cloud-notifications-graphql-service/pom.xml
Labels: dependencies

#1323 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1327 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1329 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1318 AAE-19581 Upgrade Activiti Cloud to Spring Boot 3.2.1
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
  pom.xml
Labels: dependencies

#1335 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1342 fix(versions): update Activiti/activiti-cloud versions into 8.1.x
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1341 fix(versions): update Activiti/activiti-cloud versions into develop
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot
