Repository Activiti/activiti-cloud, pull requests merged in 2024-08, with the labels that each got.

#1494 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.11
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1501 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.12
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1484 AAE-24320 Limit the scope of Audit event export data
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/conf/AuditJPAAutoConfiguration.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/controllers/AuditEventsAdminControllerImpl.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/repository/EventsRepository.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/main/java/org/activiti/cloud/services/audit/jpa/service/AuditEventsAdminService.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/controller/EventsEngineEventsAdminControllerIT.java
  activiti-cloud-audit-service/activiti-cloud-services-audit-jpa/src/test/java/org/activiti/cloud/services/audit/jpa/service/AuditEventsAdminServiceTest.java
Labels: preview

#1502 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.15
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1509 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.16
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1468 AAE-23395 Upgrade-to-spring-boot-3.3.1
  activiti-cloud-build/activiti-cloud-build-dependencies-parent/pom.xml
  activiti-cloud-notifications-graphql-service/services/ws/pom.xml
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/test/resources/org/activiti/cloud/common/swagger/apidocs/springdoc-api-docs.json
  pom.xml
Labels: do-not-merge, preview

#1513 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.17
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1515 AAE-25410 Spring boot revert to 3.2.9
  activiti-cloud-api/pom.xml
  activiti-cloud-build/activiti-cloud-build-dependencies-parent/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/test/resources/org/activiti/cloud/common/swagger/apidocs/springdoc-api-docs.json
  activiti-cloud-service-common/pom.xml
  pom.xml
Labels: preview

#1519 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.19
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop
