Repository Activiti/activiti-cloud, pull requests merged in 2024-02, with the labels that each got.

#1345 fix(versions): update Activiti/activiti-cloud versions into 7.11.x
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot

#1351 AAE-20229 Fix for error message when launching /graphiql from Query service
  activiti-cloud-notifications-graphql-service/services/graphiql/src/main/java/org/activiti/cloud/services/notifications/graphql/graphiql/GraphiQLIndexController.java
  activiti-cloud-notifications-graphql-service/services/graphiql/src/test/java/org/activiti/cloud/services/notifications/graphql/graphiql/GraphiQLAutoConfigurationTest.java
Labels: bug

#1348 AAE-19748 Fix for GET tasks API maxItems ignored when the variable filter is used
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-repo/src/main/java/org/activiti/cloud/services/query/app/repository/CustomizedTaskRepositoryImpl.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryTasksIT.java
Labels: bug

#1352 AAE-20169 Fix GET /process-instances/{id}/tasks api request is ignoring paged and sort parameters
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-repo/src/main/java/org/activiti/cloud/services/query/app/repository/CustomizedTaskRepositoryImpl.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryTasksIT.java
Labels: bug

#1355 chore(deps): upgrade Activiti/Activiti to version 8.3.0-alpha.7
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1358 chore(deps): upgrade Activiti/Activiti to version 8.3.0-alpha.8
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1359 AAE-20417 reduce logging on websocket connection errors
  activiti-cloud-notifications-graphql-service/services/ws/src/main/java/org/activiti/cloud/services/notifications/graphql/ws/transport/GraphQLBrokerSubProtocolHandler.java
Labels: bug

#1360 chore(deps): upgrade Activiti/Activiti to version 8.3.0-alpha.9
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1361 chore(deps): upgrade Activiti/Activiti to version 8.3.0-alpha.10
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1366 chore(deps): upgrade Activiti/Activiti to version 8.3.0-alpha.11
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1373 chore(deps): upgrade Activiti/Activiti to version 8.3.0-alpha.12
  activiti-cloud-api/pom.xml
  activiti-cloud-modeling-service/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop
