Repository Activiti/activiti-cloud, pull requests merged in 2024-09, with the labels that each got.

#1527 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.21
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1528 AAE-25756 Add missing indexes for task owner, assignee and process instance initiator in the Query service schema
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-liquibase/src/main/resources/config/query/liquibase/changelog/25-alter.oracle.schema.8.7.0.sql
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-liquibase/src/main/resources/config/query/liquibase/changelog/25-alter.pg.schema.8.7.0.sql
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-liquibase/src/main/resources/config/query/liquibase/changelog/h2.schema.sql
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-liquibase/src/main/resources/config/query/liquibase/master.xml
Labels: enhancement

#1529 AAE-25704 Make Task variable filters and Process variable filter work simultaneously
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/conf/HibernateConfiguration.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/dialect/CustomPostgreSQLDialect.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/dialect/DoubleQuotedStringType.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/dialect/JsonValueFunctions.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/dialect/RelationalFormType.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/specification/TaskSpecification.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/RestrictVariableEntityQueryIT.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskAdminControllerIT.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskControllerHelperIT.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskSearchIT.java
Labels: bug

#1532 AAE-23173 Upgrade apache mime4j to 0.8.11
  activiti-cloud-service-common/pom.xml
Labels: dependencies

#1533 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.22
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1538 AAE-23429 Upgrade transitive classgraph dependency to 4.8.175
  activiti-cloud-acceptance-tests/pom.xml
  activiti-cloud-audit-service/activiti-cloud-audit-dependencies/pom.xml
  activiti-cloud-notifications-graphql-service/dependencies/pom.xml
  activiti-cloud-query-service/activiti-cloud-query-dependencies/pom.xml
  pom.xml
Labels: dependencies

#1542 AAE-25874 Drop index on process variable when field type changes from text to jsonb
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-liquibase/src/main/resources/config/query/liquibase/master.xml
Labels: do-not-merge

#1545 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.23
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1552 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.24
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1548 AAE-26067 Spring boot upgrade to 3.3.4
  activiti-cloud-api/pom.xml
  activiti-cloud-audit-service/activiti-cloud-starter-audit-consumer/src/test/java/org/activiti/cloud/starter/audit/consumer/test/ActivitiAuditConsumerAutoConfigurationTest.java
  activiti-cloud-build/activiti-cloud-build-dependencies-parent/pom.xml
  activiti-cloud-query-service/activiti-cloud-starter-query-consumer/src/test/java/org/activiti/cloud/starter/query/consumer/test/ActivitiQueryConsumerIT.java
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/FunctionBindingConfiguration.java
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/test/resources/org/activiti/cloud/common/swagger/apidocs/springdoc-api-docs.json
  activiti-cloud-service-common/pom.xml
  pom.xml
Labels: preview
