Repository Activiti/activiti-cloud, pull requests merged in 2024-06, with the labels that each got.

#1449 AAE-22377 Exception if user exceed pagination limit
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/CommonExceptionHandlerQuery.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskEntityControllerIT.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/resources/swagger-expected.json
  activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/main/java/org/activiti/cloud/alfresco/argument/resolver/AlfrescoPageArgumentMethodResolver.java
  activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/main/java/org/activiti/cloud/alfresco/config/AlfrescoWebAutoConfiguration.java
  activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/main/resources/config/alfresco-rest-config.properties
  activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/test/java/org/activiti/cloud/alfresco/argument/resolver/AlfrescoPageArgumentMethodResolverTest.java
  activiti-cloud-service-common/activiti-cloud-services-dbp-rest/src/test/java/org/activiti/cloud/alfresco/config/AlfrescoWebAutoConfigurationTest.java
Labels: enhancement, preview

#1467 chore(deps): upgrade Activiti/Activiti to version 8.6.0-alpha.6
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1469 AAE-23393 New endpoint to get application versions for process instances
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceAdminController.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceAdminService.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessInstancesEntityIT.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/resources/swagger-expected.json
  activiti-cloud-service-common/activiti-cloud-services-test/src/main/java/org/activiti/cloud/starters/test/builder/ProcessInstanceEventContainedBuilder.java
Labels: enhancement

#1473 AAE-23314 Upgrade alfresco-build-tools to version 5.30.0
  .github/workflows/create-github-prerelease.yaml
  .github/workflows/main.yml
  .github/workflows/pr-closed.yaml
  .github/workflows/versions-propagation-auto-merge.yml
Labels: bug

#1471 AAE-23482 use codeflow for Swagger UI API
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/main/java/org/activiti/cloud/common/swagger/springdoc/BaseOpenApiBuilder.java
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/test/resources/org/activiti/cloud/common/swagger/apidocs/springdoc-api-docs.json
Labels: preview

#1474 AAE-23492 Task search performance regression when searching by task variable name and value (#1472)
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/pom.xml
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/conf/QueryRestControllersAutoConfiguration.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskControllerHelper.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/resources/query-rest.properties
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskAdminControllerIT.java
Labels: preview
