Repository Activiti/activiti-cloud, pull requests merged in 2025-02, with the labels that each got.

#1672 AAE-30789 Fix GraphQL request processing failed: java.lang.NullPointerException
  activiti-cloud-notifications-graphql-service/pom.xml
Labels: bug

#1673 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.2
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1684 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.3
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1690 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.4
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1692 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.5
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1699 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.7
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1700 AAE-30844 Use ordered controller advice
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/CommonExceptionHandlerQuery.java
Labels: enhancement, preview
