Repository Activiti/activiti-cloud, pull requests merged in 2025-04, with the labels that each got.

#1770 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.34
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1778 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.36
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1782 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.37
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, CI, develop

#1783 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.38
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1771 AAE-32880 Constant and static values are not fetched properly
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/main/java/org/activiti/cloud/services/core/ProcessDefinitionValuesService.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/test/java/org/activiti/cloud/services/core/ProcessDefinitionValuesServiceTest.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessDefinitionAdminControllerImplIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/MessageIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ProcessDefinitionIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/resources/access-control.properties
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/resources/processes/MessageIT-extensions.json
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/resources/processes/MessageIT.bpmn20.xml
Labels: preview
