Repository Activiti/activiti-cloud, pull requests merged in 2025-03, with the labels that each got.

#1696 AAE-31637 Spring boot update with hibernate downgrade
  activiti-cloud-acceptance-scenarios/identity-adapter-acceptance-tests/pom.xml
  activiti-cloud-acceptance-scenarios/pom.xml
  activiti-cloud-api/activiti-cloud-api-process-model-impl/pom.xml
  activiti-cloud-api/activiti-cloud-api-task-model-impl/pom.xml
  activiti-cloud-build/activiti-cloud-build-dependencies-parent/pom.xml
  activiti-cloud-examples/activiti-cloud-query/rest/src/test/java/org/activiti/cloud/query/rest/QueryRestApplicationIT.java
  activiti-cloud-query-service/activiti-cloud-services-query/activiti-cloud-services-query-model/pom.xml
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryAdminProcessDiagramIT.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessDefinitionCandidateStartersIT.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessDefinitionIT.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessInstancesEntityIT.java
  activiti-cloud-query-service/activiti-cloud-starter-query/src/test/resources/swagger-expected.json
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-api/pom.xml
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-connectors/pom.xml
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/RuntimeBundleExceptionHandler.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ConnectorDefinitionControllerImplIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/pom.xml
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/helper/ProcessInstanceRestTemplate.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ProcessInstanceIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/runtime/ProcessVariablesIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/swagger/RuntimeBundleSwaggerIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/swagger/RuntimeBundleSwaggerITSupport.java
  activiti-cloud-service-common/activiti-cloud-service-common-liquibase/src/main/java/org/activiti/cloud/common/liquibase/SpringLiquibaseConfigurationSupport.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/FunctionAnnotationService.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/FunctionBindingConfiguration.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ConnectorConfigurationIT.java
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/main/java/org/activiti/cloud/common/swagger/springdoc/conf/SwaggerAutoConfiguration.java
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/main/java/org/activiti/cloud/common/swagger/springdoc/customizer/CustomOperationIdCustomizer.java
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/main/java/org/activiti/cloud/common/swagger/springdoc/customizer/NamingOperationCustomizer.java
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/test/java/org/activiti/cloud/common/swagger/apidocs/TestSwaggerSpringdocConfig.java
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/test/java/org/activiti/cloud/common/swagger/springdoc/customizer/NamingOperationCustomizerTest.java
  activiti-cloud-service-common/activiti-cloud-services-swagger/src/test/resources/org/activiti/cloud/common/swagger/apidocs/springdoc-api-docs.json
  activiti-cloud-service-common/pom.xml
  pom.xml
Labels: preview

#1708 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.14
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1723 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.17
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1735 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.18
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1745 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.20
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1748 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.25
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1750 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.26
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1762 AAE-33181 Revert "build(deps): bump org.springframework.cloud:spring-cloud-dependencies from 2024.0.0 to 2024.0.1 (#1752)"
  activiti-cloud-build/activiti-cloud-build-dependencies-parent/pom.xml
Labels: dependencies, CI

#1763 AAE-33028 Add constant values decorator to admin process definitions endpoint
  activiti-cloud-api/activiti-cloud-api-process-model-impl/src/main/java/org/activiti/cloud/api/process/model/impl/CloudProcessDefinitionImpl.java
  activiti-cloud-api/activiti-cloud-api-process-model/src/main/java/org/activiti/cloud/api/process/model/ExtendedCloudProcessDefinition.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/main/java/org/activiti/cloud/services/core/ProcessDefinitionValuesService.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/main/java/org/activiti/cloud/services/core/conf/ServicesCoreAutoConfiguration.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/main/java/org/activiti/cloud/services/core/decorator/ProcessDefinitionConstantValuesDecorator.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/test/java/org/activiti/cloud/services/core/ProcessDefinitionValuesServiceTest.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/test/java/org/activiti/cloud/services/core/decorator/ProcessDefinitionConstantValuesDecoratorTest.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/assemblers/ToCloudProcessDefinitionConverter.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessDefinitionAdminControllerImpl.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessDefinitionControllerImpl.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessDefinitionAdminControllerImplIT.java
Labels: enhancement

#1764 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.30
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1765 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.31
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1766 chore(deps): upgrade Activiti/Activiti to version 8.8.0-alpha.32
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1768 AAE-33554 Trigger health check failure for missing durable queues
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/ActivitiCloudMessagingProperties.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/ActivitiCloudMessagingAutoConfiguration.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/resources/config/activiti-cloud-messaging.properties
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ActivitiCloudMessagingAutoConfigurationTests.java
Labels: enhancement
