Repository Activiti/activiti-cloud, pull requests merged in 2025-01, with the labels that each got.

#1645 AAE-29208 Add Activiti Spring Cache Manager provider
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/main/java/org/activiti/cloud/services/core/conf/ServicesCoreAutoConfiguration.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/main/java/org/activiti/cloud/services/core/decorator/ProcessDefinitionVariablesDecorator.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-core/src/test/java/org/activiti/cloud/services/core/decorator/ProcessDefinitionVariablesDecoratorTest.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/configuration/CloudEventsAutoConfiguration.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/main/java/org/activiti/cloud/services/events/converter/ToCloudVariableEventConverter.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-events/src/test/java/org/activiti/cloud/services/events/converter/ToCloudVariableEventConverterTest.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessDefinitionControllerImpl.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessDefinitionControllerImplIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/test/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceVariableControllerImplIT.java
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/main/resources/metadata.properties
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/conf/EngineConfigurationIT.java
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/main/java/org/activiti/cloud/services/identity/keycloak/config/ActivitiKeycloakAutoConfiguration.java
  activiti-cloud-service-common/activiti-cloud-services-common-identity-keycloak/src/main/resources/keycloak-client.properties
  activiti-cloud-service-common/activiti-cloud-services-common-security/pom.xml
  activiti-cloud-service-common/activiti-cloud-services-common-security/src/main/java/org/activiti/cloud/services/common/security/config/CommonSecurityAutoConfiguration.java
  activiti-cloud-service-common/activiti-cloud-services-common-security/src/main/resources/config/activiti-cloud-services-common-security.properties
  activiti-cloud-service-common/activiti-cloud-services-common-security/src/test/java/org/activiti/cloud/security/authorization/AuthorizationConfigurerIT.java
  activiti-cloud-service-common/activiti-cloud-services-common-security/src/test/java/org/activiti/cloud/security/authorization/SecurityTestConfiguration.java
  activiti-cloud-service-common/pom.xml
Labels: enhancement

#1656 AAE-29225 Fix consumer throws missing anonymous queue exception
  activiti-cloud-notifications-graphql-service/starter/src/test/java/org/activiti/cloud/notifications/graphql/starter/ActivitiGraphQLWsNativeStarterIT.java
  activiti-cloud-notifications-graphql-service/starter/src/test/resources/application.properties
  activiti-cloud-notifications-graphql-service/starter/src/test/resources/h2-init.sql
  activiti-cloud-runtime-bundle-service/activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/cmdendpoint/CommandEndpointIT.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/pom.xml
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/ActivitiCloudMessagingProperties.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/java/org/activiti/cloud/common/messaging/config/ActivitiCloudMessagingAutoConfiguration.java
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/main/resources/config/activiti-cloud-messaging.properties
  activiti-cloud-service-common/activiti-cloud-service-messaging-config/src/test/java/org/activiti/cloud/common/messaging/config/test/ActivitiCloudMessagingAutoConfigurationTests.java
Labels: bug

#1663 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.50
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1667 chore(deps): upgrade Activiti/Activiti to version 8.7.0-alpha.51
  activiti-cloud-api/pom.xml
  activiti-cloud-query-service/pom.xml
  activiti-cloud-runtime-bundle-service/pom.xml
  activiti-cloud-service-common/pom.xml
Labels: updatebot, develop

#1671 AAE-30697 Fix Activiti Cloud Keycloak test container is timing out during integration tests
  activiti-cloud-service-common/activiti-cloud-services-test-containers/src/main/java/org/activiti/cloud/services/test/containers/KeycloakContainerApplicationInitializer.java
Labels: bug
